// SwitchMTP — a macOS MTP client for Nintendo Switch running DBI.
// Copyright (C) 2025 fratei
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License version 2 as published by
// the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.

package nxmtp

import (
	"os"
	"path/filepath"
	"time"

	"github.com/ganeshrvel/go-mtpfs/mtp"
)

// MakeDirectory creates a directory, including any missing parents.
func (c *Client) MakeDirectory(storageID uint32, fullPath string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	st, err := c.storageByID(storageID)
	if err != nil {
		return err
	}
	if !st.Capabilities.MakeDirectory {
		return &Error{Kind: KindReadOnly, Op: "makeDirectory",
			Msg: "cannot create directories on \"" + st.DisplayName + "\""}
	}

	fullPath = NormalizePath(fullPath)
	if fullPath == "/" {
		return errf(KindInvalidInput, "makeDirectory", "cannot create the storage root")
	}
	_, err = c.ensureDirectory(storageID, fullPath)
	return err
}

// makeDirectoryAt creates one directory inside a known parent.
//
// MTP has no mkdir: a directory is an object whose format is Association,
// created with SendObjectInfo and no following SendObject.
func (c *Client) makeDirectoryAt(storageID, parent uint32, name string) (uint32, error) {
	info := &mtp.ObjectInfo{
		StorageID:        storageID,
		ObjectFormat:     mtp.OFC_Association,
		AssociationType:  mtp.AT_GenericFolder,
		ParentObject:     parent,
		Filename:         deviceSafeName(name),
		ModificationDate: now(),
		CaptureDate:      now(),
	}
	_, _, handle, err := c.t.SendObjectInfo(storageID, parent, info)
	if err != nil {
		return 0, classify("makeDirectory", err)
	}
	return handle, nil
}

// Delete removes files and directories.
//
// Directories are removed depth-first: MTP responders generally refuse to
// delete a non-empty Association, and DBI is no exception.
func (c *Client) Delete(storageID uint32, paths []string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	st, err := c.storageByID(storageID)
	if err != nil {
		return err
	}
	if !st.Capabilities.Delete {
		return &Error{Kind: KindReadOnly, Op: "delete",
			Msg:  "cannot delete from \"" + st.DisplayName + "\"",
			Hint: deleteHint(st)}
	}

	for _, p := range paths {
		if err := c.checkCancelled(); err != nil {
			return err
		}
		norm := NormalizePath(p)
		if norm == "/" {
			return errf(KindInvalidInput, "delete", "refusing to delete the storage root")
		}
		node, err := c.resolvePath(storageID, norm)
		if err != nil {
			if KindOf(err) == KindNotFound {
				continue // already gone
			}
			return err
		}
		if err := c.deleteRecursive(storageID, norm, node); err != nil {
			return err
		}
		c.cache.invalidate(storageID, norm)
	}
	return nil
}

func (c *Client) deleteRecursive(storageID uint32, p string, node cachedNode) error {
	if node.isFolder {
		entries, err := c.listRaw(storageID, node.handle)
		if err != nil {
			return err
		}
		for _, e := range entries {
			child := JoinPath(p, e.Name)
			if err := c.deleteRecursive(storageID, child, cachedNode{handle: e.Handle, isFolder: e.IsFolder}); err != nil {
				return err
			}
		}
	}
	if err := c.t.DeleteObject(node.handle); err != nil {
		return classify("delete "+p, err)
	}
	return nil
}

func deleteHint(st *Storage) string {
	if st.Virtual {
		return "\"" + st.DisplayName + "\" is generated by the console and does not contain real files."
	}
	return ""
}

// Rename changes an object's name in place.
//
// This requires SetObjectPropValue, which is optional in MTP. If the device
// did not advertise it, we say so plainly instead of failing with a bare
// protocol error -- and the UI will already have greyed the action out, since
// it reads the same capability flag.
func (c *Client) Rename(storageID uint32, fullPath, newName string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	st, err := c.storageByID(storageID)
	if err != nil {
		return err
	}
	if !st.Capabilities.Rename {
		return &Error{
			Kind: KindUnsupported,
			Op:   "rename",
			Msg:  "this device does not support renaming",
			Hint: "The Switch's MTP responder did not advertise the SetObjectPropValue operation. " +
				"You can copy the file to your Mac, rename it there, and copy it back.",
		}
	}

	fullPath = NormalizePath(fullPath)
	node, err := c.resolvePath(storageID, fullPath)
	if err != nil {
		return err
	}

	safe := deviceSafeName(newName)
	if safe == "" {
		return errf(KindInvalidInput, "rename", "invalid name")
	}

	parent, _, err := c.resolveParent(storageID, fullPath)
	if err != nil {
		return err
	}
	if _, err := c.findChild(storageID, parent, safe); err == nil {
		return errf(KindAlreadyExists, "rename", "%q already exists", safe)
	}

	if err := c.t.SetObjectPropValue(node.handle, mtp.OPC_ObjectFileName, &mtp.StringValue{Value: safe}); err != nil {
		if IsUnsupported(err) {
			c.demoteCap(mtp.OC_MTP_SetObjectPropValue)
			return &Error{Kind: KindUnsupported, Op: "rename",
				Msg:  "this device does not support renaming",
				Hint: "The device advertised renaming but rejected it."}
		}
		return classify("rename", err)
	}

	c.cache.invalidate(storageID, fullPath)
	c.cache.invalidate(storageID, JoinPath(pathDir(fullPath), safe))
	return nil
}

// BackupSaves downloads an entire storage into a timestamped local directory.
//
// This is the one workflow where a plain recursive download is not quite
// enough: the destination needs to be unambiguous and self-describing, because
// restoring the wrong save is destructive and irreversible.
func (c *Client) BackupSaves(storageID uint32, destination string, onProgress ProgressFunc) (*TransferSummary, error) {
	c.mu.Lock()
	st, err := c.storageByID(storageID)
	if err != nil {
		c.mu.Unlock()
		return nil, err
	}
	name := st.DisplayName
	c.mu.Unlock()

	stamp := now().Format("2006-01-02-150405")
	dir := filepath.Join(destination, "SwitchMTP-"+sanitizeLocalName(name)+"-"+stamp)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, wrapErr(KindLocalIO, "backupSaves", err)
	}

	summary, err := c.Download(DownloadRequest{
		StorageID:       storageID,
		Sources:         []string{"/"},
		Destination:     dir,
		PreprocessFiles: true,
	}, nil, onProgress)
	if err != nil {
		return nil, err
	}
	summary.Note = "Backed up to " + dir
	writeBackupManifest(dir, c.ref, name, summary)
	return summary, nil
}

// writeBackupManifest records what was backed up, so a restore months later is
// not guesswork. A failure here is not worth failing the backup over.
func writeBackupManifest(dir string, ref DeviceRef, storage string, s *TransferSummary) {
	content := "SwitchMTP backup\n" +
		"Created:  " + now().Format(time.RFC3339) + "\n" +
		"Device:   " + ref.DisplayName + " (" + ref.ID() + ")\n" +
		"Storage:  " + storage + "\n" +
		"Files:    " + itoa(s.TotalFiles) + "\n" +
		"Bytes:    " + itoa(s.TotalBytes) + "\n"
	_ = os.WriteFile(filepath.Join(dir, "BACKUP-INFO.txt"), []byte(content), 0o644)
}

func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [24]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
